In [16]:
import numpy as np

In [4]:
from sklearn.datasets import make_classification
X, y = make_classification(n_classes=2, class_sep=0.5,
weights=[0.05, 0.95], n_informative=2, n_redundant=0, flip_y=0,
n_features=2, n_clusters_per_class=1, n_samples=1000, random_state=10)

In [8]:
X

array([[-0.26943684, -0.79156516],
       [-0.8365411 , -0.31013335],
       [-0.48761304, -0.64150224],
       ...,
       [-2.36469491,  0.92237279],
       [-0.74061427, -0.19914068],
       [-1.95164137,  0.50807884]])

In [9]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [6]:
X.shape

(1000, 2)

In [30]:
print(pd.DataFrame([]))

Empty DataFrame
Columns: []
Index: []


In [7]:
y.shape

(1000,)

In [17]:
np.bincount(y)

array([ 50, 950])

In [31]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(pd.DataFrame(X), pd.DataFrame(y))

In [34]:
y_res.value_counts()

1    950
0    950
dtype: int64

In [22]:
import requests
import json
import time
from datetime import datetime
import pandas as pd

In [23]:
import numpy as np
from numpy import savetxt
from numpy import asarray
from matplotlib import pyplot as plt
from os import listdir
from os.path import isfile, join

In [25]:
def viewAllDataFromFolder(dataPath,prefix):
    onlyfiles = [f for f in listdir(dataPath) if isfile(join(dataPath, f))]
    count = 0
    fileLs = []
    lsBdTrain = None
    dataList = []
    for fs in onlyfiles:
        if fs[:2]==prefix:
            print(fs)
            count = count + 1
            dataItem = pd.read_pickle(dataPath+"/"+fs)
            dataList.append(dataItem)
    frame = pd.concat(dataList)
    return frame

In [26]:
dataset = viewAllDataFromFolder("CBT/data","8-")

8-1629576360-tan-k2-1.pkl
8-1629487770-tan-k3-0.pkl
8-1629797400-tan-k3-0.pkl
8-1629944340-tan-k3-0.pkl
8-1629810600-tan-km-1.pkl
8-1629660180-tan-km-1.pkl
8-1629634500-tan-k3-0.pkl
8-1629660180-tan-k2-1.pkl
8-1629793080-tan-k2-1.pkl
8-1629876780-tan-km-1.pkl
8-1629397800-tan-k2-1.pkl
8-1629397800-tan-km-1.pkl
8-1629876780-tan-k2-1.pkl
8-1629797400-tan-k2-1.pkl
8-1629713460-tan-km-1.pkl
8-1629793080-tan-km-1.pkl
8-1629978780-tan-k3-0.pkl
8-1629944340-tan-k2-1.pkl
8-1629367800-tan-km-1.pkl
8-1629367800-tan-k2-1.pkl
8-1629576360-tan-k3-0.pkl
8-1629612720-tan-km-1.pkl
8-1629944340-tan-km-1.pkl
8-1629314880-tan-km-1.pkl
8-1629634500-tan-k2-1.pkl
8-1629487770-tan-k2-1.pkl
8-1629797400-tan-km-1.pkl
8-1629487770-tan-km-1.pkl
8-1629489780-tan-km-1.pkl
8-1629576360-tan-km-1.pkl
8-1629397800-tan-k3-1.pkl
8-1629461730-tan-k2-1.pkl
8-1629978780-tan-k2-1.pkl
8-1629461730-tan-k3-0.pkl
8-1629489780-tan-k2-1.pkl
8-1629660180-tan-k3-0.pkl
8-1629612720-tan-k3-0.pkl
8-1629314880-tan-k2-1.pkl
8-1629793080

In [27]:
dataset = dataset.reset_index().fillna(0)
dataset.head()

timestamp  cpu_system  cpu_idle  cpu_user  cpu_iowait  pod_count  \
0  1.629576e+09    0.024000  0.906000  0.052667    0.000333        6.0   
1  1.629576e+09    0.024000  0.906000  0.052667    0.000333        6.0   
2  1.629576e+09    0.034333  0.895667  0.045667    0.003000        6.0   
3  1.629576e+09    0.034333  0.895667  0.045667    0.003000        6.0   
4  1.629576e+09    0.025000  0.908000  0.045000    0.000000        6.0   

   system_load     mem_total     mem_avail   disk_io  disk_space_used  \
0         0.12  1.911521e+09  2.174521e+09  0.005067         0.534038   
1         0.12  1.911521e+09  2.174521e+09  0.005067         0.534038   
2         0.10  1.911755e+09  2.174288e+09  0.010400         0.534295   
3         0.10  1.911755e+09  2.174288e+09  0.010400         0.534295   
4         0.07  1.911210e+09  2.174833e+09  0.000800         0.534296   

    net_received   net_transmit    node  label  
0  951905.066667  899240.000000  tan-k2      1  
1  951905.066667  899240.000000  tan-k2      1  
2  771843.200000  541984.000000  tan-k2      1  
3  771843.200000  541984.000000  tan-k2      1  
4  849244.266667  771101.333333  tan-k2      1

In [57]:
dataset.shape

(170130, 24)

In [28]:
print("Data Shape",dataset.shape)
print("Label counts:")
print(dataset["label"].value_counts())
print("8 data item per 1 minute")
print((dataset.shape[0] / 8)/60," hours")
print(((dataset.shape[0] / 8)/60)/24," days")
print("Num of data item with 10 min:",(dataset.shape[0] / 8)/10)

Data Shape (170130, 15)
Label counts:
1    124212
0     45918
Name: label, dtype: int64
8 data item per 1 minute
354.4375  hours
14.768229166666666  days
Num of data item with 10 min: 2126.625


In [42]:
dataset["timemm"] = dataset['timestamp']
dataset['timemm'] = dataset['timemm'].apply(lambda x: datetime.fromtimestamp(x))
dataset["year"] = dataset['timemm'].apply(lambda x:x.year)
dataset["month"] = dataset['timemm'].apply(lambda x:x.month)
dataset["day"] = dataset['timemm'].apply(lambda x:x.day)
dataset["hour"] = dataset['timemm'].apply(lambda x:x.hour)
dataset["minute"] = dataset['timemm'].apply(lambda x:x.minute)
dataset["second"] = dataset['timemm'].apply(lambda x:x.second)
del dataset['timemm']

dataset["node"] = dataset["node"].apply(lambda x : 2 if x=="tan-k2" else 3 if x=="tan-k3" else 1 if x=="tan-km" else x)
dataset["cpu_total"] = 1 - dataset["cpu_idle"]

dataset["cpu_user_rate"] = dataset["cpu_user"] / dataset["cpu_total"]
dataset["cpu_system_rate"] = dataset["cpu_system"] / dataset["cpu_total"]

In [49]:
def resampleData(dataset,label):
    dataX = dataset.drop(label, axis=1)
    dataY = dataset[label]
    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(dataX, dataY)
    result = pd.concat([X_res, y_res], axis=1)
    return result

In [50]:
reDataset = resampleData(dataset,"label")
#echo 1 > /proc/sys/vm/overcommit_memory : Fix the problem of memory errors

In [55]:
reDataset["label"].value_counts()

1    124212
0    124212
Name: label, dtype: int64

In [53]:
!sudo apt-get install foremost


/bin/sh: 1: sudo: not found


In [54]:
dataset

timestamp  cpu_system  cpu_idle  cpu_user  cpu_iowait  pod_count  \
0       1.629576e+09    0.024000  0.906000  0.052667    0.000333        6.0   
1       1.629576e+09    0.024000  0.906000  0.052667    0.000333        6.0   
2       1.629576e+09    0.034333  0.895667  0.045667    0.003000        6.0   
3       1.629576e+09    0.034333  0.895667  0.045667    0.003000        6.0   
4       1.629576e+09    0.025000  0.908000  0.045000    0.000000        6.0   
...              ...         ...       ...       ...         ...        ...   
170125  1.629576e+09    0.000000  0.000000  0.000000    0.000000        2.0   
170126  1.629576e+09    0.000000  0.000000  0.000000    0.000000        2.0   
170127  1.629576e+09    0.000000  0.000000  0.000000    0.000000        2.0   
170128  1.629576e+09    0.000000  0.000000  0.000000    0.000000        2.0   
170129  1.629576e+09    0.000000  0.000000  0.000000    0.000000        2.0   

        system_load     mem_total     mem_avail   disk_io  ...  label  year  \
0              0.12  1.911521e+09  2.174521e+09  0.005067  ...      1  2021   
1              0.12  1.911521e+09  2.174521e+09  0.005067  ...      1  2021   
2              0.10  1.911755e+09  2.174288e+09  0.010400  ...      1  2021   
3              0.10  1.911755e+09  2.174288e+09  0.010400  ...      1  2021   
4              0.07  1.911210e+09  2.174833e+09  0.000800  ...      1  2021   
...             ...           ...           ...       ...  ...    ...   ...   
170125         0.00  0.000000e+00  0.000000e+00  0.000000  ...      0  2021   
170126         0.00  0.000000e+00  0.000000e+00  0.000000  ...      0  2021   
170127         0.00  0.000000e+00  0.000000e+00  0.000000  ...      0  2021   
170128         0.00  0.000000e+00  0.000000e+00  0.000000  ...      0  2021   
170129         0.00  0.000000e+00  0.000000e+00  0.000000  ...      0  2021   

        month  day  hour  minute  second  cpu_total  cpu_user_rate  \
0           8   21    20       6       0   0.094000       0.560284   
1           8   21    20       6       8   0.094000       0.560284   
2           8   21    20       6      16   0.104333       0.437700   
3           8   21    20       6      24   0.104333       0.437700   
4           8   21    20       6      32   0.092000       0.489130   
...       ...  ...   ...     ...     ...        ...            ...   
170125      8   21    19      59      24   1.000000       0.000000   
170126      8   21    19      59      32   1.000000       0.000000   
170127      8   21    19      59      40   1.000000       0.000000   
170128      8   21    19      59      48   1.000000       0.000000   
170129      8   21    19      59      56   1.000000       0.000000   

        cpu_system_rate  
0              0.255319  
1              0.255319  
2              0.329073  
3              0.329073  
4              0.271739  
...                 ...  
170125         0.000000  
170126         0.000000  
170127         0.000000  
170128         0.000000  
170129         0.000000  

[170130 rows x 24 columns]

In [56]:
dataset.to_pickle("allData.pkl")

In [58]:
ls = ["1629576360","1629487770","1629797400","1629944340","1629810600","1629660180","1629634500","1629660180","1629793080","1629876780","1629397800","1629397800","1629876780","1629797400","1629713460","1629793080","1629978780","1629944340","1629367800","1629367800","1629576360","1629612720","1629944340","1629314880","1629634500","1629487770","1629797400","1629487770","1629489780","1629576360","1629397800","1629461730","1629978780","1629461730","1629489780","1629660180","1629612720","1629314880","1629793080","1629713460","1629978780","1629876780","1629612720","1629810600","1629634500","1629713460","1629314880","1629810600","1629367800","1629489780"]


In [60]:
np.array(ls).unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'